### ISSUE TITLE
Potential issue: it is possible to subscribe to store updates multiple times

### ISSUE THREAD

**Issue by garnett** [Swift-Flow/Swift-Flow#27]
Since ```subscribers``` is an array (and ```Set``` is not really possible, there is no good way for subscribers to be ```Hashable```) two consecutive ```subscribe``` calls will add subscriber two times, but ```unsubscribe``` removes only one instance.

Possible solutions:
1. Fail fast with ```assert/abort```
2. Silently ignore next subscription (maybe log something to console)

**Comment by Ben-G** [comment]
Good catch @garnett! I think we should silently ignore the second subscription. From an API perspective we guarantee that the `StoreSubscriber` will be notified of the new state when they subscribe, this promise would still hold true when we silently ignore a second subscription.

Further the API promises that a call to unsubscribe will stop the `StoreSubscriber` from receiving further updates - this promise would be held true as well.

So we ignore further subscriptions as an implementation detail. Are you interested in implementing this @garnett? Otherwise I'm happy to tackle it as well!

**Comment by garnett** [comment]
@Ben-G will be happy to do it
